# Generated by Django 3.2.9 on 2021-11-24 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ratings', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('count_in_stock', models.IntegerField(default=15)),
                ('views', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='shop')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
