# Generated by Django 3.2.9 on 2021-11-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='iamage',
            new_name='image',
        ),
    ]
