# Generated by Django 3.2.9 on 2021-11-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
