# Generated by Django 3.2.9 on 2021-11-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_paid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_token',
            new_name='token',
        ),
    ]
